version: '3'
services:
  php-app:
    image: php:7.4-apache
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
